- name: Conditions
  hosts: localhost
  tasks:
    - name: Condition1
      ansible.builtin.debug:
        msg: Welcome to devops course
      when: Course_Name == "Devops" and Trainer_Name == "Raghu"

    - name: Condition1
      ansible.builtin.debug:
        msg: Welcome to AWS course
      when: Course_Name == "AWS" or Trainer_Name == "Raghu"
  #Condition will be passed from CLI

