- name: Conditions
  hosts: localhost
  tasks:
    - name: Condition1
      ansible.builtin.debug:
        msg: Welcome to devops course
      when: (Course_Name == "Devops" and Trainer_Name == "Raghu")

    - name: Condition2
      ansible.builtin.debug:
        msg: Welcome to AWS course
      when: (Course_Name == "AWS" or Trainer_Name == "Raju")
      #Condition will be passed from CLI
# ansible-playbook Conditions.yml -e Trainer_Name=Raju -e Course_Name=GCP
# o/p AWS Statement
