- name: Loops
  hosts: localhost
  tasks:
    - name: print loops
      ansible.builtin.debug:
        msg: available courses are {{ item }}
      loop :
        - devops
        - aws

    - name: Print loops 2
      ansible.builtin.debug:
        msg: item name is {{ item["ITEM_NAME"] }} Cost is {{ item["ITEM_COST"] }}
      loop:
        - { ITEM_NAME: Apple , ITEM_COST: 20 }
        - { ITEM_NAME: Banana , ITEM_COST: 10 }