- name: Variables
  hosts: localhost
  vars:
    NAME: Santhosh
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: Name is {{ NAME }}

    - name: Print variable at task level
      ansible.builtin.debug:
        msg: Fruit1 is {{ FRUIT }}
        vars:
          FRUIT: banana

