- name: Variables
  hosts: localhost
  vars:
    NAME: Santhosh #String Data Type
  vars_files:
    - usernames.yml

  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: Name is {{ NAME }}

    - name: Print variable at task level
      ansible.builtin.debug:
        msg: Fruit1 is {{ FRUIT[0] }}, Fruit2 is {{ FRUIT[1] }}
      vars:
        FRUIT:
          - banana
          - apple

    - name: Print Variable from yml file
      ansible.builtin.debug:
        msg: File variables - {{ USER_NAME }}

